name: folly
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2
workspace:
  - packages/data
  - packages/domain

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^3.0.3
  intl: any

  domain:
    path: packages/domain
  go_router: ^16.3.0
  phosphor_flutter: ^2.1.0
  file_picker: ^10.3.6
  permission_handler: ^12.0.1
  image_picker: ^1.2.1
  path: ^1.9.1
  flutter_dotenv: ^6.0.0
  video_player: ^2.10.1
  icons_launcher: ^3.0.3
  flutter_native_splash: ^2.4.7
  flutter_local_notifications: ^19.5.0
  firebase_messaging: ^16.1.1
  firebase_core: ^4.4.0
  loader_overlay: ^5.0.0
  lottie: ^3.3.2
  expandable_text: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3
  melos: ^7.3.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/lotties/empty.json
    - assets/lotties/lemony.json

flutter_intl:
  enabled: true

melos:
  scripts:
    generate: 
      run: melos exec -c 1 --depends-on build_runner -- dart run build_runner build